from termcolor import colored

# Function to display instructions
def display_instructions():
    print(colored("Instructions:", "yellow"))
    print("1. Getting Started:")
    print("   - To begin, ensure you have a text file (.txt) ready with the text you want to process.")
    print("   - When you start the program, you'll be presented with a main menu.")
    print()
    print("2. Main Menu:")
    print("   - Upon starting the program, you'll see the main menu with the following options:")
    print("     - Instructions: Select this option to view the instructions.")
    print("     - Input File: Choose this option to provide the path to the input text file (.txt).")
    print("     - Process: After providing the input file, select this option to perform all processing steps together.")
    print("     - More Options: If you wish to explore individual processing steps, select this option.")
    print()
    print("3. Providing Input File:")
    print("   - Select the 'Input File' option from the main menu.")
    print("   - Enter the full path of the text file you want to process. Note that the file must be in .txt format.")
    print()
    print("4. Processing Text:")
    print("   - After providing the input file, select the 'Process' option from the main menu.")
    print("   - The program will then perform the following processing steps:")
    print("     - Convert the text to lowercase.")
    print("     - Tokenize the text into words.")
    print("     - Perform part-of-speech tagging.")
    print("     - Perform named entity recognition.")
    print("     - Analyze word frequency.")
    print("     - Generate an analysis report.")
    print()
    print("5. More Options:")
    print("   - If you want to explore individual processing steps or perform concatenated operations, select the 'More Options' from the main menu.")
    print("   - You'll be presented with detailed options to perform specific processing steps.")
    print()
    print("6. Exiting the Program:")
    print("   - To exit the program, simply select the 'Exit' option from the main menu.")
    print()
    print("Remember, at any point, if you encounter any issues or need further assistance, feel free to reach out.")
    print()
